### ISSUE TITLE
Doesn't work right in FF22

### ISSUE THREAD

**Issue by windwakr** [leibovic/about-me#14]
Doesn't show any sites.

See image: http://i.imgur.com/Wc4P30X.png

**Comment by berteh** [comment]
Exactly same screen on install of the addon in FF25.0 running on ubuntu 12.10, missing "most visited sites" stats.

Downloads stats do show downloads completed after the addon was installed though... but not the whole history of downloads.  Is there the same date-based filter on the navigation history?

Would be nice to have the option to display stats for a selected period / whole history.

thanks!

PS: this may be an issue with big history (as I recon from windwakr stats, mine is about 10k sites for last 2 months, whole "places.sqlite" file is ~10Mb).

**Comment by leibovic** [comment]
Any reason in particular you're running FF25? 26 was released over 6 weeks ago, and 27 will be released soon. The add-on is updated to work properly in 26.

**Comment by berteh** [comment]
You're quite right: "recent sites" works indeed fine after a browser update, sorry for the time lost and thanks for the nice extension.
B.
